### ISSUE TITLE
service of skor can connect with database but don't response when insert data to postgres 

### ISSUE THREAD

**Issue by skl-songkiat** [hasura/skor#16]
Hi i have problem about response web hook  

i can build skor.c and run with command "./build/skor 'host=localhost port=5432 dbname=postgres user=postgres password=' http://localhost:5000 " and then i try insert data to postgres but
don't response when insert data to postgres 

i don't know that what i did wrong

<img width="1440" alt="screen shot 2561-05-14 at 18 55 47" src="https://user-images.githubusercontent.com/13052473/39996812-f3545954-57aa-11e8-9d96-9a88cdbae283.png">

**Comment by sidmutha** [comment]
Hi
Did you set up the triggers in Postgres?

**Comment by skl-songkiat** [comment]
no i didn't do that trigger but insert manually to postgres

**Comment by skl-songkiat** [comment]
i get it now , Thank you
