### ISSUE TITLE
Query generated by gen-triggers.py failed on Postgres 9.6

### ISSUE THREAD

**Issue by pthm** [hasura/skor#18]
When attempting to execute the query I am receiving the following error on Postgres 9.6

```
ERROR:  syntax error at or near "CASCADE"
LINE 1: ...NCTION public.notify_skor_github_repositories_insert CASCADE
                                                                ^
QUERY:  DROP FUNCTION public.notify_skor_github_repositories_insert CASCADE
CONTEXT:  PL/pgSQL function inline_code_block line 6 at EXECUTE
```

It executes correctly on Postgres 10 but unfortunately am stuck on 9.6 in production so cannot install the triggers correctly.

Is it just not supported or can the query be modified to be compatible?

**Comment by 0x777** [comment]
Thanks for taking time to fix this
